### ISSUE TITLE
Balances not visible on testnets

### ISSUE THREAD

**Issue by mwx27** [ProphetFund/peanut-ui#65]
When I am on https://peanut.to/send and see the modal with chains, there is no visible balance on any testnet, while mainnet balances work cool.

Tested on updated Chrome + Metamask

**Comment by borcherd** [comment]
Hey there,

Thanks for reaching out. Just wanted to let you know that we don't show balances for testnets on purpose. Testnets are mostly for devs and folks testing things out, so we figured it's not necessary to load up all the balance details for all testnets we support.

Loading testnet balances means a lot of extra RPC calls, and since it's only testnet funds, we thought it's best to keep things simpler and smoother. This way, we can focus on making sure everything runs great on the mainnet, where the real action happens.

Hope this makes sense! If you've got any more questions or feedback, feel free to drop them here.
