### ISSUE TITLE
Claiming funds by other wallet address in same browser

### ISSUE THREAD

**Issue by mwx27** [ProphetFund/peanut-ui#66]
After successful creating link with GoerliEth, I tried to claim it.
First by the same wallet, at first some error occured and appeared message "Something went wrong while claiming".
After a while I tried second time and it was successful.

Secondly I created again the link and tried to claim by another wallet. So I pasted the link url in a new tab and changed wallet address in Metamask. The new address was visible in address button in right top corner of site. I clicked claim, but the funds went to wrong address - it just came back to the address from which it had been sent before.

Tested on updated Chrome + Metamask

**Comment by borcherd** [comment]
Hey,

Thanks for flagging this with us. For the first part, where you got a "Something went wrong while claiming" message – it's a bit of a hiccup that can happen. Sometimes things like estimating gas can get a bit wonky. If you run into this, giving it another shot is usually the way to go, just like you did.

About the second issue, it sounds like the wallet mix-up happened because you were still connected with your original account in Metamask. When you switch accounts in Metamask, make sure to also update the connection to the dapp. A quick disconnect and reconnect with your new wallet should do the trick. This helps the dapp recognize which account you're actually trying to use.

Hope this clears things up! If you've got more questions or something else pops up, just let us know.

**Comment by mwx27** [comment]
IMO what I see on your UI and what happens there should be definitely strictly linked with active wallet address on Metamask (or other plugin). Otherwise it can always lead to some confusions among users that use more than one EVM address

**Comment by 0xkkonrad** [comment]
reopening this

**Comment by borcherd** [comment]
Thanks for noticing & reopening! SC bug which will be fixed in the next major release!
